authy/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

app_name = "authy"

urlpatterns = [ 
    path("profile/", views.UserProfile, name="profile"),
    path("profile-other/<str:username>", views.OtherUserProfile, name="profile_other"),
]

dashboard/urls.py
from django.urls import path, include
from .import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.views import LoginView
from authy.views import UserProfile, OtherUserProfile
from post.views import NewPost

urlpatterns = [
    path("", views.home, name="home"),
    path('sign-up/', views.register, name="register"),
    path('login/', auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name='login'),
    path("logout/", views.logout_user, name="logout"),
    
    # =========== TESTING ============#
    # path('test/', views.test, name="test")
]

instagramClone/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("users/", include('authy.urls')),
    path('', include('dashboard.urls')),
    path('', include('post.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.index, name="index"),
    path('newpost/', views.NewPost, name="newPost"),
    path("tag/<slug:tag_slug>/", views.tags, name="tags"),
    path("<uuid:post_id>/like/", views.like, name="postLike")
]

dashboard/models.py
from django.db import models
import datetime

class DataUser(models.Model):
    username = models.CharField(max_length=255)
    second_username = models.CharField(max_length=255)
    email = models.EmailField(max_length=100)
    

dashboard/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
# from .models import Record

class UserRegisterForm(UserCreationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username', 'class': 'prompt srch_explore'}), max_length=50, required=True)
    # username = forms.EmailInput(widget=forms.TextInput(attrs={'placeholder': 'Username'}), max_length=50, required=True)

    email = forms.EmailField(widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'prompt srch_explore'}))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Enter Password', 'class': 'prompt srch_explore'}))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'prompt srch_explore'}))
    # email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

dashboard/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.template import loader
from django.contrib.auth.decorators import login_required

from .forms import UserRegisterForm
from .models import DataUser
from post.models import Post,Tag, Stream, Follow 
from post.models import Post, Stream

@login_required
def home(request):    
    all_users = User.objects.all()
    userData = DataUser.objects.all()
    user = request.user
    posts = Stream.objects.filter(user=request.user)
    
    # Testing User
    print(f"User: {user} - ID: {user.id}")
    print(f"Posts for User {user}: {posts}")
    
    group_ids = []
    
    for post in posts:
        print(f"Post ID: {post.post.id}") 
        group_ids.append(post.post_id)
        
    post_items = Post.objects.filter(id__in=group_ids).all().order_by('-posted')
    
    # Post Debug
    print(post_items)
    
    context = {
        'all_users': all_users,
        'userData': userData,
        'post_items': post_items,
        'profile_user': user
    }
    return render(request, 'dashboard/home.html', context)

@login_required
def logout_user(request):
    logout(request)
    messages.success(request, "You Have Been Logged Out....")
    return redirect('home')

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            # Profile.get_or_create(user=request.user)
            username = form.cleaned_data.get('username')
            messages.success(request, f'Hurray your account was created!!')

            # Automatically Log In The User
            new_user = authenticate(username=form.cleaned_data['username'],
                                    password=form.cleaned_data['password1'],)
            login(request, new_user)
            return redirect('home')
    elif request.user.is_authenticated:
        return redirect('home')
    else:
        form = UserRegisterForm()
    return render(request, 'register.html', {'form': form})

def logout_user(request):
    logout(request)
    return redirect('login')


#================= TESTING ================#

# def test(request):

    # post_items = Stream.objects.all()
    
    # template = loader.get_template('dashboard/test.html')
    
    # context = {
    #     'post_items': post_items
    # }
    
    # return render(request, 'dashboard/test.html', {})

# def PostTest(request):
#     user = request.user
    
#     post_items = Stream.objects.all().filter(user=user)
#     if request.method == 'POST':
#         picture = Post.objects.get['picture']
#         caption = Post.objects.get['caption']
#         tags_forms = Post.objects.get['tags']
        
#         form = Stream.objects.get_or_create(picture=picture, caption=caption, tags=tags_forms, user=user)
        
#         group_ids = []
        
#         for group_id in group_ids:
#             group_id.append()
#             print(int(group_id))

dashboard/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %}</title>

    <link rel="stylesheet" href="{% static "css/style.css" %}">
    <link rel="stylesheet" href="{% static "asset3/css/style.css" %}">
    <link rel="stylesheet" href="{% static "asset4/css/style.css" %}">

    <link href="https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css" rel="stylesheet" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
    />

    <!-- bootstrap -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous" />
  </head>
  <body>
    {% block sidebar %}{% endblock %} {% block content %}{% endblock %}
    <!-- bootstrap -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    {% comment %} js {% endcomment %}
    <script src="{% static "js/action-user-profile.js" %}"></script>
    <script src="{% static "js/main.js" %}"></script>
  </body>
</html>

dashboard/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
    <link rel="stylesheet" href="{% static 'assets2/style.css' %}" />
    <title>Instagram | Login</title>
  </head>

  <body>
    <div id="wrapper">
      <div class="container">
        <div class="phone-app-demo"></div>
        <div class="form-data">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="logo">
              <img src="{% static 'assets2/images/logo.png' %}" alt="logo" />
            </div>
              {{form}}  
            <button class="form-btn" type="submit">Log in</button>
            <span class="has-separator">Or</span>
            <a class="facebook-login" href="#"> <i class="fab fa-facebook-square"></i> Log in with Facebook </a>
            <a class="password-reset" href="#">Forgot password?</a>
          </form>
          <div class="sign-up">Don't have an account? <a href="{% url "register" %}">Sign up</a></div>
          <div class="get-the-app">
            <span>Get the app.</span>
            <div class="badges">
              <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge" />

              <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

dashboard/templates/register.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <script src="https://kit.fontawesome.com/fc1e235b2e.js"></script>
    <link rel="stylesheet" href="{% static 'assets2/style.css' %}" />
    <title>Instagram | Register</title>
  </head>

  <body>
    <div id="wrapper">
      <div class="container">
        <div class="phone-app-demo"></div>
        <div class="form-data">
          <form action="" method="POST">
            {% csrf_token %}
            <div class="logo">
              <img src="{% static 'assets2/images/logo.png' %}" alt="logo" />
            </div>
            {{form.username}} {{form.email}} {{form.password1}} {{form.password2}}
            <button class="form-btn" type="submit">Sign In</button>

            <span class="has-separator">Or</span>
            <a class="facebook-login" href="#"> <i class="fab fa-facebook-square"></i> Log in with Facebook </a>
            <a class="password-reset" href="#">Forgot password?</a>
          </form>
          <div class="sign-up">Have an account? <a href="{% url 'login' %}">Login </a></div>
          <div class="get-the-app">
            <span>Get the app.</span>
            <div class="badges">
              <img src="{% static 'assets2/images/app-store.png' %}" alt="app-store badge" />
              <img src="{% static 'assets2/images/google-play.png' %}" alt="google-play badge" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

dashboard/templates/sidebar.html
{% extends "base.html" %} {% load static %} {% load crispy_forms_tags %}

{% block content %}
 <!-- sidebar -->
  <div class="item sidebar position-fixed">
    <div class="logo"><img src="{% static "asset/img/logo.png" %}" alt="logo-instagram" class="nav-link mt-4 ms-3" /></div>

    <div class="menu-sidebar mt-4">
      <div class="sidebar-link">
          <a href="\" class="home fw-semibold ms-3"
             ><span class="icon icon-home fs-2"><i class="bx bxs-home"></i></span> <span class="span-text ms-3 fw-bold fs-5" style="margin-top: -10px">Home</span>
          </a>
         
          <a href="#" class="search ms-3"
             ><span class="icon fs-2"><i class="bx bx-search"></i></span> <span class="span-text ms-3">Search</span>
          </a>
         
          <a href="#" class="explore ms-3"
             ><span class="icon fs-4"><i class="fa-regular fa-compass"></i></span> <span class="span-text">Explore</span>
          </a>
         
          <a href="#" class="reels ms-3"><span class="icon fs-2"><img src="{% static "asset/icons/icon-rels.png" %}" alt="" width="26" style="margin-bottom: 5px" /></span> <span class="span-text">Reels</span> </a>
         
          <a href="#" class="messages ms-3"><span class="icon fs-2"><img src="{% static "asset/icons/icon-message.png" %}" alt="" width="25" style="margin-bottom: 5px" /></span> <span class="span-text">Messages</span> </a>
         
          <a href="#" class="notifications"
             ><span class="icon fs-2"><i class="bx bx-heart"></i></span> <span class="span-text ms-3">Notifications</span>
          </a>
         
          <a class="create ms-3" onclick="createNewPost()" style="cursor: pointer"><span class="icon fs-2"><img src="{% static "asset/icons/icon-create.png" %}" alt="" width="23" style="margin-bottom: 5px" /></span> <span class="span-text">Create</span> </a>
            <div class="slide position-absolute">
              <div class="close" id="close" onclick="closeCreatePost()"><i class="fa-solid fa-xmark text-white"></i></div>
              <div class="create-post rounded-3">
                <div class="title text-center" style="padding: 10px 20px; height: 45px; width: 100%;">
                  <p class="fw-bold">Create new post</p>
                </div>
                <div class="upload-content-1">
                  <div class="icon">
                    <img src="{% static "asset/icons/icon-create-post.png" %}" width="150" alt="">
                  </div>
                  <div class="text-create-post">
                    <p class="text-center fs-5">Drag photos and videos here</p>
                  </div>
                  <div class="button-create-post text-center">
                     <button  class="btn" style="background-color: #1877f2; color: #fff"><a href="{% url "newPost" %}" class="text-white">Select from computer</a></button>
                  </div>
                </div>
              </div>
            </div>
         
          <a href="{% url "authy:profile" %}" class="profile ms-1"
             ><span class="icon fs-2"><img src="{% static "asset/profile-img/my-profile.jpg" %}" alt="" width="28" style="margin-bottom: 8px" class="rounded-circle" /></span> <span class="span-text">Profile</span>
          </a>
      </div>

      <label for="more" class="mt-5 more" style="margin-left: 20px; cursor: pointer">
        <span class="icon"><i class="fa-solid fa-bars fs-4"></i></span> 
        <span class="span-text" style="margin: 0 0 0 22px">More</span>
      </label>

      <input type="checkbox" id="more" style="display: none;">

      <div class="more-container position-absolute rounded-4" style="margin-top: -505px; width: 276px; margin-left: 15px">
        <ul>
          <li><a href="#" class="text-decoration-none text-dark"><i class='bx bxs-cog fs-4 position-absolute'></i> <span style="margin-left: 40px;">Setting</span></a></li>
          <li><a href="#" class="text-decoration-none text-dark"><i class="fa-solid fa-chart-line fs-4 position-absolute"></i> <span style="margin-left: 40px">Your activity</span></a></li>
          <li><a href="#" class="text-decoration-none text-dark"><i class='bx bx-bookmark fs-4 position-absolute'></i> <span style="margin-left: 40px">Saved</span></a></li>
          <li><a href="#" class="text-decoration-none text-dark"><i class='bx bx-sun fs-4 position-absolute'></i> <span style="margin-left: 40px">Switch apperance</span></a></li>
          <li class="top-border"><a href="#" class="text-decoration-none text-dark"><i class='bx bx-message-alt-error fs-4 position-absolute'></i> <span style="margin-left: 40px">Report a problem</span></a></li>
          <li class="bottom-border"><a href="#" class="text-decoration-none text-dark"><i class="fa-brands fa-threads fs-4 position-absolute"></i> <span style="margin-left: 40px;">Threads</span></a></li>
          <li><a href="#" class="text-decoration-none text-dark">Switch account</a></li>
          <li><a href="{% url "logout" %}" class="text-decoration-none text-dark">Logout</a></li>
        </ul>
      </div>
    </div>
  </div>
{% endblock  %}